### PR TITLE
Capitalize relation names 

### LINKED ISSUE #988: ovsdb2ddlog produces bad DDlog when OVSDB tables start with lowercase letters.
When an OVSDB schema has a table whose name begins with a lowercase letter, `ovsdb2ddlog` uses it verbatim as the name of a DDlog relation, which causes `ddlog` to reject it.  For example, with the following OVSDB schema cut down from the Open vSwitch schema:

```
{"name": "Open_vSwitch",
 "tables": {
   "sFlow": {
     "columns": {
       "targets": {
         "type": {"key": "string", "min": 1, "max": "unlimited"}},
       "sampling": {
         "type": {"key": "integer", "min": 0, "max": 1}},
       "polling": {
         "type": {"key": "integer", "min": 0, "max": 1}},
       "header": {
         "type": {"key": "integer", "min": 0, "max": 1}},
       "agent": {
         "type": {"key": "string", "min": 0, "max": 1}},
       "external_ids": {
         "type": {"key": "string", "value": "string",
                  "min": 0, "max": "unlimited"}}}}}}
```

`ovsdb2ddlog` produces the following ddlog:

```
import ovsdb


/* Input relations */

input relation sFlow (
    _uuid: uuid,
    targets: Set<string>,
    sampling: Option<integer>,
    polling: Option<integer>,
    header: Option<integer>,
    agent: Option<string>,
    external_ids: Map<string,string>
)
primary key (x) x._uuid

/* Output relations */


/* Delta tables definitions */
```

which yields the following `ddlog` error:

```
error: failed to parse input file: "foo.dl" (line 6, column 16):
unexpected sFlow
expecting "&" or relation name
```

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
Fixes #988

### CODE REVIEW

**Comment by ryzhyk** [comment]
I suspect you will also need to change the rust runtime component.

**Comment by mbudiu-vmw** [comment]
Can you briefly explain why/which?

**Comment by mbudiu-vmw** [comment]
@blp: how can I test this change? I don't know how to change table names in OVN.

**Comment by mbudiu-vmw** [comment]
@ryzhyk has explained why this change is not enough. There is some Rust code that handles the communication between OVSDB and DDlog. That code has to know about the capitalization change as well. If OVSDB table names are case insensitive, then this change may just work. Otherwise the situation becomes more complicated: we will need to make the ovsdb2ddlog compiler generate a map with the original and modified names of all relations, which would be loaded by the runtime to perform the translation. 
@blp: are table names case-sensitive in OVS DB?

**Comment by blp** [comment]
> @blp: are table names case-sensitive in OVS DB?

Yes.

**Comment by blp** [comment]
> @ryzhyk has explained why this change is not enough. There is some Rust code that handles the communication between OVSDB and DDlog. That code has to know about the capitalization change as well. If OVSDB table names are case insensitive, then this change may just work. Otherwise the situation becomes more complicated: we will need to make the ovsdb2ddlog compiler generate a map with the original and modified names of all relations, which would be loaded by the runtime to perform the translation.

Another possibility is to have the runtime perform the same transformation as ovsdb2ddlog.

**Comment by mbudiu-vmw** [comment]
But we have to inform the runtime about the right name of the table. DDlog will only contain the uppercase one.

**Comment by blp** [comment]
Oh, right.

DDlog supports annotation with `#[attributes]`, can those help here?

**Comment by mbudiu-vmw** [comment]
so you are suggesting adding an annotation to the declaration `#[original="something"]`.
That may work.

**Comment by ryzhyk** [comment]
That's a good idea

**Comment by mbudiu-vmw** [comment]
I will try to make this work.

**Comment by mbudiu-vmw** [comment]
After heroic fights with Rust I have managed to add a new annotation #[original="name"] which can be placed on relations only. This annotation indicates the original relation name if the program is generated by a tool. This is used by the ovsdb generator to recover the original table name, which may be lowercase, and thus not a legal DDlog relation name.
@blp I would appreciate help testing this with ovn, didn't know how to do it myself.

File: src/Language/DifferentialDatalog/Compile.hs [hunk 1]
```diff
@@ -1421,6 +1425,47 @@ mkRelId2NameC =
...
+    where
+    entries = map mkrel $ M.elems $ progRelations d
+    mkrel :: Relation -> Doc
+    mkrel rel = (doubleQuotes $ pp $ name rel) <+> "=> Some(&\"" <> pp (origRelName rel) <> "\"),"
+
+-- Generates a function that converts original relation names into relation names
+-- Original names are obtained via the 'original' attribute
+mkOrigRelName2Name :: DatalogProgram -> Doc
+mkOrigRelName2Name d =
+    "pub fn orig_rel_name2name(rname: &str) -> ::std::option::Option<&'static str> {" $$
```
Comment (mbudiu-vmw) [inline src/Language/DifferentialDatalog/Compile.hs:1458]: note that this generated function is currently not used by any API

File: src/Language/DifferentialDatalog/Attribute.hs [hunk 2]
```diff
@@ -140,6 +141,20 @@ fieldValidateAttr d attr = do
          "deserialize_from_array" -> return ()
          n -> err d (pos attr) $ "Unknown attribute " ++ n
 
+relValidateAttr :: (MonadError String me) => DatalogProgram -> Attribute -> me ()
+relValidateAttr d attr = do
+    case name attr of
+         "original" -> case attrVal attr of
+              E (EString _ _) -> return ()
+              _ -> err d (pos attr) $ "Attribute 'original' should be followed by a string"
```
Comment (ryzhyk) [inline src/Language/DifferentialDatalog/Attribute.hs:149]: A better error message would be 
```
"The value of the 'original' attribute should be a string, e.g., #[original=\"Foo\"]"
```

File: src/Language/DifferentialDatalog/OVSDB/Compile.hs [hunk 3]
```diff
@@ -229,11 +241,12 @@ mkTable' tkind t@Table{..} = do
     let key = if tkind == TableInput
                  then "primary key (x) x._uuid"
                  else empty
+    let annotation = tableAnnotation t
     if tableIsInterned t && tkind == TableInput
     then return $ "typedef" <+> pp tname <+> "=" <+> pp tname <+> "{"                   $$
                   (nest' $ vcommaSep columns)                                           $$
                   "}"                                                                   $$
-                  prefix <+> "relation" <+> pp tname <+> "[Intern<" <> pp tname <> ">]" $$
+                  annotation <+> prefix <+> "relation" <+> pp tname <+> "[Intern<" <> pp tname <> ">]" $$
```
Comment (ryzhyk) [inline src/Language/DifferentialDatalog/OVSDB/Compile.hs:249]: Perhaps, change
```
annotation <+> ...
```

to 
```
annotation $$
...
```

File: rust/template/src/ovsdb_api.rs [hunk 4]
```diff
@@ -128,7 +129,9 @@ fn dump_delta(
                 rel.iter()
                     .map(|(v, w)| {
                         assert!(*w == 1);
-                        record_into_insert_str(v.clone().into_record(), table_str)
+                        record_into_insert_str(v.clone().into_record(), table_str, &|t| {
+                            prog.get_table_original_name(t)
+                        })
```
Comment (Kixiron) [inline rust/template/src/ovsdb_api.rs:134]: This is really neat, it makes me wonder if we shouldn't also store the *current* name so that we can improve errors somewhat

File: rust/template/ovsdb/lib.rs [hunk 5]
```diff
@@ -227,11 +227,17 @@ fn record_from_val(v: Value) -> Result<Record, String> {
     }
 }
 
+type NameTranslator<'a> = &'a dyn Fn(&'a str) -> Result<&'static str, String>;
+
```
Comment (Kixiron) [inline rust/template/ovsdb/lib.rs:231]: This is very limiting, it should be a generic instead of forcing dynamic dispatch
```suggestion
```

File: rust/template/ovsdb/lib.rs [hunk 6]
```diff
@@ -227,11 +227,17 @@ fn record_from_val(v: Value) -> Result<Record, String> {
...
 /*
  * Functions to convert DDlog Records to JSON
  */
 
-pub fn record_into_insert_str(rec: Record, table: &str) -> Result<String, String> {
+pub fn record_into_insert_str<'a>(
+    rec: Record,
+    table: &'a str,
+    translator: NameTranslator<'a>,
+) -> Result<String, String> {
```
Comment (Kixiron) [inline rust/template/ovsdb/lib.rs:240]:
```suggestion
pub fn record_into_insert_str<'a, F>(
    rec: Record,
    table: &'a str,
    translator: F,
) -> Result<String, String>
where
    F: FnOnce(&'a str) -> Result<&'static str, String>,
{
```

File: rust/template/src/ovsdb_api.rs [hunk 7]
```diff
@@ -128,7 +129,9 @@ fn dump_delta(
                 rel.iter()
                     .map(|(v, w)| {
                         assert!(*w == 1);
-                        record_into_insert_str(v.clone().into_record(), table_str)
+                        record_into_insert_str(v.clone().into_record(), table_str, &|t| {
```
Comment (Kixiron) [inline rust/template/src/ovsdb_api.rs:132]: With the `record_into_insert_str()` change this reference isn't needed
```suggestion
                        record_into_insert_str(v.clone().into_record(), table_str, |t| {
```

File: rust/template/src/ovsdb_api.rs (hunk 4 above)
Comment (Kixiron) [inline rust/template/src/ovsdb_api.rs:134]:
```suggestion
                        record_into_insert_str(v.clone().into_record(), table_str, &|table| {
                            prog.get_table_original_name(table)
                        })
```

File: rust/template/src/ovsdb_api.rs [hunk 8]
```diff
@@ -283,11 +290,11 @@ pub unsafe extern "C" fn ddlog_into_ovsdb_update_str(
     res
 }
 
-fn into_update_str(table: *const c_char, rec: &Record) -> Result<CString, String> {
+fn into_update_str(prog: &HDDlog, table: *const c_char, rec: &Record) -> Result<CString, String> {
     let table_str: &str = unsafe { CStr::from_ptr(table) }
         .to_str()
         .map_err(|e| format!("{}", e))?;
-    record_into_update_str(rec.clone(), table_str)
+    record_into_update_str(rec.clone(), table_str, &|t| prog.get_table_original_name(t))
```
Comment (Kixiron) [inline rust/template/src/ovsdb_api.rs:297]:
```suggestion
    record_into_update_str(rec.clone(), table_str, |t| prog.get_table_original_name(t))
```

File: rust/template/src/ovsdb_api.rs [hunk 9]
```diff
@@ -342,9 +350,13 @@ fn dump_output(
...
-                            record_into_insert_str(v.clone().into_record(), table_str)
+                            record_into_insert_str(v.clone().into_record(), table_str, &|t| {
+                                prog.get_table_original_name(t)
+                            })
                         } else {
-                            record_into_delete_str(v.clone().into_record(), table_str)
+                            record_into_delete_str(v.clone().into_record(), table_str, &|t| {
+                                prog.get_table_original_name(t)
+                            })
                         }
```
Comment (Kixiron) [inline rust/template/src/ovsdb_api.rs:360]: These branches are incredibly similar
```suggestion
                        let recorder = if (*w == 1) {
                            record_into_insert_str
                        } else {
                            record_into_delete_str
                        };
                        let get_table_name = |table| prog.get_table_original_name(t);
                        let record = v.clone().into_record();

                        recorder(record, table_str, get_table_name);
```

File: src/Language/DifferentialDatalog/Compile.hs [hunk 10]
```diff
@@ -1421,6 +1425,47 @@ mkRelId2NameC =
...
+    "pub fn rel_name2orig_name(rname: &str) -> ::std::option::Option<&'static str> {" $$
+    "   match rname {"                                        $$
+    (nest' $ nest' $ vcat $ entries)                          $$
+    "       _  => None"                                       $$
+    "   }"                                                    $$
+    "}"
+    where
+    entries = map mkrel $ M.elems $ progRelations d
+    mkrel :: Relation -> Doc
+    mkrel rel = (doubleQuotes $ pp $ name rel) <+> "=> Some(&\"" <> pp (origRelName rel) <> "\"),"
```
Comment (Kixiron) [inline src/Language/DifferentialDatalog/Compile.hs:1452]:
```suggestion
    mkrel rel = (doubleQuotes $ pp $ name rel) <+> "=> ::core::option::Some(\"" <> pp (origRelName rel) <> "\"),"
```

File: src/Language/DifferentialDatalog/Compile.hs [hunk 11]
```diff
@@ -1421,6 +1425,47 @@ mkRelId2NameC =
...
+    "pub fn orig_rel_name2name(rname: &str) -> ::std::option::Option<&'static str> {" $$
+    "   match rname {"                                        $$
+    (nest' $ nest' $ vcat $ entries)                          $$
+    "       _  => None"                                       $$
+    "   }"                                                    $$
+    "}"
+    where
+    entries = map mkrel $ M.elems $ progRelations d
+    mkrel :: Relation -> Doc
+    mkrel rel = (doubleQuotes $ pp $ origRelName rel) <+> "=> Some(&\"" <> pp (name rel) <> "\"),"
```
Comment (Kixiron) [inline src/Language/DifferentialDatalog/Compile.hs:1467]:
```suggestion
    mkrel rel = (doubleQuotes $ pp $ origRelName rel) <+> "=> ::core::option::Some(\"" <> pp (name rel) <> "\"),"
```

File: rust/template/differential_datalog/src/ddlog.rs [hunk 12]
```diff
@@ -23,6 +23,10 @@ pub trait DDlogInventory {
     /// Convert a `RelId` into its symbolic name.
     fn get_table_name(&self, tid: RelId) -> Result<&'static str, String>;
 
+    /// Given a table name, the the original name (from the 'original' DDlog
```
[the remark this answers is not in the document]
Comment (mbudiu-vmw) [reply rust/template/differential_datalog/src/ddlog.rs:26]: As you commented below, this always returns a value, so I will keep it Result. The String is there because all other functions in this group have the same signature,. BTW: we may probably want to add this to the C API too.

File: rust/template/ovsdb/lib.rs (hunk 5 above)
Comment (mbudiu-vmw) [reply rust/template/ovsdb/lib.rs:231]: Can you please write the suggested replacement? It took me 2 days to figure out even this one.

File: rust/template/differential_datalog/src/ddlog.rs (hunk 12 above)
[the remark this answers is not in the document]
Comment (ryzhyk) [reply rust/template/differential_datalog/src/ddlog.rs:26]: > As you commented below, this always returns a value, so I will keep it Result

In that case, documentation should be more clear about this.

> BTW: we may probably want to add this to the C API too.

As well as Java and Go :-/

**Comment by blp** [comment]
> @blp I would appreciate help testing this with ovn, didn't know how to do it myself.

The https://github.com/blp/ovs-reviews/tree/ddlog-controller branch is the one that ran into that. In that branch controller/automake.mk has a workaround:

```
	$(AM_V_GEN)$(OVSDB2DDLOG) -f $< $(controller_ovs_opts) | sed 's/sFlow/SFlow/g' > $@.tmp && mv $@.tmp $@
```

If you remove the `sed` invocation there then you'd see whether this works.

File: rust/template/ovsdb/lib.rs (hunk 5 above)
Comment (Kixiron) [reply rust/template/ovsdb/lib.rs:231]: Unfortunately not, trait aliases aren't stable yet

**Comment by mbudiu-vmw** [comment]
Haven't tried Ben's test yet, but I have added the function to the C/Java/Go APIs.

**Comment by ryzhyk** [comment]
> > @blp I would appreciate help testing this with ovn, didn't know how to do it myself.
> 
> The https://github.com/blp/ovs-reviews/tree/ddlog-controller branch is the one that ran into that. In that branch controller/automake.mk has a workaround:
> 
> ```
> 	$(AM_V_GEN)$(OVSDB2DDLOG) -f $< $(controller_ovs_opts) | sed 's/sFlow/SFlow/g' > $@.tmp && mv $@.tmp $@
> ```
> 
> If you remove the `sed` invocation there then you'd see whether this works.

@blp, will this test the actual ddlog-to-OVSDB communication or just compile the schema?

**Comment by blp** [comment]
> @blp, will this test the actual ddlog-to-OVSDB communication or just compile the schema?

It just compiles the schema. We don't have anything that exercises it yet.

**Comment by mbudiu-vmw** [comment]
This has passed all the tests. If @blp confirms it's what is needed, we can merge this.

File: src/Language/DifferentialDatalog/Compile.hs [hunk 13]
```diff
@@ -1423,6 +1428,66 @@ mkRelId2NameC =
...
+                      _                   -> pp $ relName rel
+
+-- Generates a function that converts relation names into the original relation names
+-- (obtained via the 'original' attribute)
+mkRelName2OrigName :: DatalogProgram -> Doc
+mkRelName2OrigName d =
+    "pub fn rel_name2orig_name(rname: &str) -> ::std::option::Option<&'static str> {" $$
+    "   match rname {"                                        $$
+    (nest' $ nest' $ vcat $ entries)                          $$
+    "       _  => None"                                       $$
```
Comment (Kixiron) [inline src/Language/DifferentialDatalog/Compile.hs:1449]:
```suggestion
    "       _  => ::core::option::None"                                       $$
```

File: src/Language/DifferentialDatalog/Compile.hs [hunk 14]
```diff
@@ -1423,6 +1428,66 @@ mkRelId2NameC =
...
+
+-- Generates a function that converts relation names into the original relation names
+-- (obtained via the 'original' attribute)
+mkRelName2OrigNameC :: DatalogProgram -> Doc
+mkRelName2OrigNameC d =
+    "#[cfg(feature = \"c_api\")]"                                                                   $$
+    "pub fn rel_name2orig_cname(rname: &str) -> ::std::option::Option<&'static ::std::ffi::CStr> {" $$
+    "   match rname {"                                        $$
+    (nest' $ nest' $ vcat $ entries)                          $$
+    "       _  => None"                                       $$
```
Comment (Kixiron) [inline src/Language/DifferentialDatalog/Compile.hs:1465]:
```suggestion
    "       _  => ::core::option::None"                                       $$
```

File: src/Language/DifferentialDatalog/Compile.hs [hunk 15]
```diff
@@ -1423,6 +1428,66 @@ mkRelId2NameC =
...
+    "   }"                                                    $$
+    "}"
+    where
+    entries = map mkrel $ M.elems $ progRelations d
+    mkrel :: Relation -> Doc
+    mkrel rel = (doubleQuotes $ pp $ origRelName rel) <+> "=>" <+>
+            "Some(::std::ffi::CStr::from_bytes_with_nul(b\"" <> pp (name rel) <> "\\0\")" <+>
```
Comment (Kixiron) [inline src/Language/DifferentialDatalog/Compile.hs:1472]:
```suggestion
            "::core::option::Some(::std::ffi::CStr::from_bytes_with_nul(b\"" <> pp (name rel) <> "\\0\")" <+>
```

File: src/Language/DifferentialDatalog/Compile.hs [hunk 16]
```diff
@@ -1423,6 +1428,66 @@ mkRelId2NameC =
...
+
+-- Generates a function that converts original relation names into relation names
+-- Original names are obtained via the 'original' attribute
+-- (The generated code is currently not exposed in any API)
+mkOrigRelName2Name :: DatalogProgram -> Doc
+mkOrigRelName2Name d =
+    "pub fn orig_rel_name2name(rname: &str) -> ::std::option::Option<&'static str> {" $$
+    "   match rname {"                                        $$
+    (nest' $ nest' $ vcat $ entries)                          $$
+    "       _  => None"                                       $$
```
Comment (Kixiron) [inline src/Language/DifferentialDatalog/Compile.hs:1483]:
```suggestion
    "       _  => ::core::option::None"                                       $$
```

File: rust/template/src/ovsdb_api.rs [hunk 17]
```diff
@@ -246,12 +255,14 @@ pub unsafe extern "C" fn ddlog_into_osvdb_delete_str(
     res
 }
 
-fn into_delete_str(table: *const c_char, rec: &Record) -> Result<CString, String> {
+fn into_delete_str(prog: &HDDlog, table: *const c_char, rec: &Record) -> Result<CString, String> {
```
Comment (Kixiron) [inline rust/template/src/ovsdb_api.rs:258]:
```suggestion
unsafe fn into_delete_str(prog: &HDDlog, table: *const c_char, rec: &Record) -> Result<CString, String> {
```

This function takes an arbitrary pointer and dereferences it, it's not safe

File: rust/template/src/ovsdb_api.rs [hunk 18]
```diff
@@ -283,12 +294,14 @@ pub unsafe extern "C" fn ddlog_into_ovsdb_update_str(
     res
 }
 
-fn into_update_str(table: *const c_char, rec: &Record) -> Result<CString, String> {
+fn into_update_str(prog: &HDDlog, table: *const c_char, rec: &Record) -> Result<CString, String> {
```
Comment (Kixiron) [inline rust/template/src/ovsdb_api.rs:297]:
```suggestion
unsafe fn into_update_str(prog: &HDDlog, table: *const c_char, rec: &Record) -> Result<CString, String> {
```

Ditto

File: rust/template/src/ovsdb_api.rs [hunk 19]
```diff
@@ -318,6 +331,7 @@ pub unsafe extern "C" fn ddlog_dump_ovsdb_output_table(
 }
 
 fn dump_output(
```
Comment (Kixiron) [inline rust/template/src/ovsdb_api.rs:333]:
```suggestion
unsafe fn dump_output(
```

Ditto

File: rust/template/src/ovsdb_api.rs [hunk 20]
```diff
@@ -103,6 +103,7 @@ pub unsafe extern "C" fn ddlog_dump_ovsdb_delta_tables(
 }
 
 fn dump_delta(
+    prog: &HDDlog,
```
Comment (Kixiron) [inline rust/template/src/ovsdb_api.rs:106]:
```suggestion
unsafe fn dump_delta(
    prog: &HDDlog,
```
Ditto

File: src/Language/DifferentialDatalog/Attribute.hs [hunk 21]
```diff
@@ -140,6 +141,20 @@ fieldValidateAttr d attr = do
          "deserialize_from_array" -> return ()
          n -> err d (pos attr) $ "Unknown attribute " ++ n
 
+relValidateAttr :: (MonadError String me) => DatalogProgram -> Attribute -> me ()
+relValidateAttr d attr = do
+    case name attr of
+         "original" -> case attrVal attr of
+              E (EString _ _) -> return ()
+              _ -> err d (pos attr) $ "The value of the 'original' attribute should be a string, e.g., #[original=\"Foo\"]"
```
Comment (Kixiron) [inline src/Language/DifferentialDatalog/Attribute.hs:149]:
```suggestion
              _ -> err d (pos attr) $ "The value of the 'original' attribute should be a string, e.g. #[original = \"Foo\"]"
```

File: src/Language/DifferentialDatalog/OVSDB/Compile.hs [hunk 22]
```diff
@@ -129,15 +129,27 @@ builtins :: String
...
 
+-- generate a legal DDlog relation name from a table name
+relationName :: Table -> Doc
+relationName t = let (c:rest) = name t in
+                 pp $ (toUpper c) : rest
+
+-- generate annotations necessary for a table declaration
+tableAnnotation :: Table -> Doc
+tableAnnotation t = if relationName t == (pp $ name t)
+                    then empty else text $ "#[original=\"" ++ name t ++ "\"]"
```
Comment (Kixiron) [inline src/Language/DifferentialDatalog/OVSDB/Compile.hs:140]:
```suggestion
                    then empty else text $ "#[original = \"" ++ name t ++ "\"]"
```

File: src/Language/DifferentialDatalog/Compile.hs (hunk 15 above)
Comment (Kixiron) [inline src/Language/DifferentialDatalog/Compile.hs:1472]: I think it'd be 100% valid to write `#[original = "foobar\0"]` so I think we should just add a quick error check that gives a compile error if the user tries it, that's much better than a panic deep within generated code deep within a user's application imo

File: src/Language/DifferentialDatalog/Attribute.hs (hunk 21 above)
Comment (mbudiu-vmw) [reply src/Language/DifferentialDatalog/Attribute.hs:149]: According to this https://en.wiktionary.org/wiki/e.g. you should use a comma after e.g. in US English.

File: src/Language/DifferentialDatalog/Compile.hs (hunk 15 above)
Comment (mbudiu-vmw) [reply src/Language/DifferentialDatalog/Compile.hs:1472]: This pattern is used a lot in the rust code, so perhaps we should actually file an issue for it rather than fix it here.

Comment (mbudiu-vmw) [reply src/Language/DifferentialDatalog/Compile.hs:1472]: Filed this: https://github.com/vmware/differential-datalog/issues/997

Comment (Kixiron) [reply src/Language/DifferentialDatalog/Compile.hs:1472]: I mean, both can be done. This code is being touched right now, may as well fix it

Comment (mbudiu-vmw) [reply src/Language/DifferentialDatalog/Compile.hs:1472]:
```
error[E0425]: cannot find function, tuple struct or tuple variant `Some` in module `core::option`
    --> src/lib.rs:1793:38
     |
1793 | ...   "Address" => ::core::option::Some(::std::ffi::CStr::from_bytes_with_nul(b"Address\0") .expect("Unreachable: A null byte was specifi...
     |                                    ^^^^ not found in `core::option`
     |
help: consider importing one of these items
```

File: rust/template/src/ovsdb_api.rs (hunk 20 above)
Comment (mbudiu-vmw) [reply rust/template/src/ovsdb_api.rs:106]:
```
warning: unnecessary `unsafe` block
   --> src/ovsdb_api.rs:111:27
    |
105 | / unsafe fn dump_delta(
106 | |     prog: &HDDlog,
107 | |     delta: &DeltaMap<DDValue>,
108 | |     module: *const c_char,
109 | |     table: *const c_char,
110 | | ) -> Result<CString, String> {
    | |____________________________- because it's nested under this `unsafe` fn
111 |       let table_str: &str = unsafe { CStr::from_ptr(table) }
    |                             ^^^^^^ unnecessary `unsafe` block
```

Comment (Kixiron) [reply rust/template/src/ovsdb_api.rs]: Yah, you can remove the inner unsafe blocks

File: java/ddlogapi.c [hunk 23]
```diff
@@ -531,6 +531,18 @@ JNIEXPORT jstring JNICALL Java_ddlogapi_DDlogAPI_ddlog_1get_1table_1name(
     return result;
 }
 
+JNIEXPORT jstring JNICALL Java_ddlogapi_DDlogAPI_ddlog_1get_1table_original1_1name(
+    JNIEnv *env, jobject obj, jlong progHandle, jstring table) {
+    const char* tbl = (*env)->GetStringUTFChars(env, table, NULL);
+    const char* result = ddlog_get_table_original_name((ddlog_prog)progHandle, tbl);
+    (*env)->ReleaseStringUTFChars(env, table, tbl);
+    if (table == NULL) {
```
Comment (ryzhyk) [inline java/ddlogapi.c:539]: Should this be `result==NULL`?

File: java/ddlogapi.c [hunk 24]
```diff
@@ -531,6 +531,18 @@ JNIEXPORT jstring JNICALL Java_ddlogapi_DDlogAPI_ddlog_1get_1table_1name(
...
+        throwDDlogException(env, "Unknown table id");
```
Comment (ryzhyk) [inline java/ddlogapi.c:540]: "table id" -> "table name"

File: rust/template/ovsdb/lib.rs [hunk 25]
```diff
@@ -258,6 +264,7 @@ pub fn record_into_insert_str(rec: Record, table: &str) -> Result<String, String
     };
     let mut m = Map::new();
     m.insert("op".to_owned(), Value::String("insert".to_owned()));
+    let table = translator(table)?;
```
[the remark this answers is not in the document]
Comment (ryzhyk) [reply rust/template/ovsdb/lib.rs:268]: The reverse translation from OVSDB to DDlog table names seems missing.  I think the affected function is `cmd_from_row_update`, specifically wherever it calls `table.to_owned()`.

**Comment by ryzhyk** [comment]
This PR breaks the OVN test, which is the one affected by the new feature.  I'm not yet sure why.

**Comment by mbudiu-vmw** [comment]
It's very hard to tell when the OVN test breaks since it usually fails in CI, so I learned not to look at it.

**Comment by mbudiu-vmw** [comment]
I see a test that timed-out after 1 hour. I don't see how that could be affected by this change.

**Comment by ryzhyk** [comment]
Pretty much all ddlog tests are failing, which is what causes the timeout, as failed tests often take longer.

```
 30: ovn -- 3 HVs, 1 LS, 3 lports/HV -- ovn-northd   ok
 31: ovn -- 3 HVs, 1 LS, 3 lports/HV -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
 32: ovn -- 2 HVs, 1 LS, 2 lports/HV -- ovn-northd   ok
 33: ovn -- 2 HVs, 1 LS, 2 lports/HV -- ovn-northd-ddlog FAILED (ovn.at:1836)
 34: ovn -- trace 1 LS, 3 LSPs -- ovn-northd         ok
 35: ovn -- trace 1 LS, 3 LSPs -- ovn-northd-ddlog   FAILED (ovn.at:2015)
 36: ovn -- 2 HVs, 4 lports/HV, localnet ports -- ovn-northd ok
 37: ovn -- 2 HVs, 4 lports/HV, localnet ports -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
 38: ovn -- vtep: 3 HVs, 1 VIFs/HV, 1 GW, 1 LS -- ovn-northd ok
 39: ovn -- vtep: 3 HVs, 1 VIFs/HV, 1 GW, 1 LS -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
 40: ovn -- 3 HVs, 1 VIFs/HV, 1 software GW, 1 LS -- ovn-northd ok
 41: ovn -- 3 HVs, 1 VIFs/HV, 1 software GW, 1 LS -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
 42: ovn -- 3 HVs, 3 LS, 3 lports/LS, 1 LR -- ovn-northd ok
 43: ovn -- 3 HVs, 3 LS, 3 lports/LS, 1 LR -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
 44: ovn -- IP relocation using GARP request -- ovn-northd ok
 45: ovn -- IP relocation using GARP request -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
 46: ovn -- portsecurity : 3 HVs, 1 LS, 3 lports/HV -- ovn-northd ok
 47: ovn -- portsecurity : 3 HVs, 1 LS, 3 lports/HV -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
 48: ovn -- 2 HVs, 2 LS, 1 lport/LS, 2 peer LRs -- ovn-northd ok
 49: ovn -- 2 HVs, 2 LS, 1 lport/LS, 2 peer LRs -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
 50: ovn -- 1 HV, 1 LS, 2 lport/LS, 1 LR -- ovn-northd ok
 51: ovn -- 1 HV, 1 LS, 2 lport/LS, 1 LR -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
 52: ovn -- 1 HV, 2 LSs, 1 lport/LS, 1 LR -- ovn-northd ok
 53: ovn -- 1 HV, 2 LSs, 1 lport/LS, 1 LR -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
 54: ovn -- 2 HVs, 3 LS, 1 lport/LS, 2 peer LRs, static routes -- ovn-northd ok
 55: ovn -- 2 HVs, 3 LS, 1 lport/LS, 2 peer LRs, static routes -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
 56: ovn -- send gratuitous arp on localnet -- ovn-northd ok
 57: ovn -- send gratuitous arp on localnet -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
 58: ovn -- 2 HVs, 3 LRs connected via LS, static routes -- ovn-northd ok
 59: ovn -- 2 HVs, 3 LRs connected via LS, static routes -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
 60: ovn -- dhcpv4 : 1 HV, 2 LS, 2 LSPs/LS -- ovn-northd ok
 61: ovn -- dhcpv4 : 1 HV, 2 LS, 2 LSPs/LS -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
 62: ovn -- dhcpv6 : 1 HV, 2 LS, 5 LSPs -- ovn-northd ok
 63: ovn -- dhcpv6 : 1 HV, 2 LS, 5 LSPs -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
 64: ovn -- 2 HVs, 2 LRs connected via LS, gateway router -- ovn-northd ok
 65: ovn -- 2 HVs, 2 LRs connected via LS, gateway router -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
 66: ovn -- icmp_reply: 1 HVs, 2 LSs, 1 lport/LS, 1 LR -- ovn-northd ok
 67: ovn -- icmp_reply: 1 HVs, 2 LSs, 1 lport/LS, 1 LR -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
 68: ovn -- policy-based routing: 1 HVs, 2 LSs, 1 lport/LS, 1 LR -- ovn-northd ok
 69: ovn -- policy-based routing: 1 HVs, 2 LSs, 1 lport/LS, 1 LR -- ovn-northd-ddlog FAILED (ovn.at:5611)
 70: ovn -- policy-based routing IPv6: 1 HVs, 3 LSs, 1 lport/LS, 1 LR -- ovn-northd ok
 71: ovn -- policy-based routing IPv6: 1 HVs, 3 LSs, 1 lport/LS, 1 LR -- ovn-northd-ddlog FAILED (ovn.at:5801)
 72: ovn -- port state up and down -- ovn-northd     ok
 73: ovn -- port state up and down -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
 74: ovn -- datapath rules added/removed -- ovn-northd ok
 75: ovn -- datapath rules added/removed -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
 76: ovn -- nd_na  -- ovn-northd                     ok
 77: ovn -- nd_na  -- ovn-northd-ddlog               FAILED (ovs-macros.at:233)
 78: ovn -- address sets modification/removal smoke test -- ovn-northd ok
 79: ovn -- address sets modification/removal smoke test -- ovn-northd-ddlog ok
 80: ovn -- ipam -- ovn-northd                       ok
 81: ovn -- ipam -- ovn-northd-ddlog                 FAILED (ovn.at:6191)
 82: ovn -- ipam connectivity -- ovn-northd          ok
 83: ovn -- ipam connectivity -- ovn-northd-ddlog    FAILED (ovn.at:6600)
 84: ovn -- ovs-vswitchd restart -- ovn-northd       ok
 85: ovn -- ovs-vswitchd restart -- ovn-northd-ddlog ok
 86: ovn -- send arp for nexthop -- ovn-northd       ok
 87: ovn -- send arp for nexthop -- ovn-northd-ddlog FAILED (ovn.at:6826)
 88: ovn -- send gratuitous arp for nat ips in localnet -- ovn-northd ok
 89: ovn -- send gratuitous arp for nat ips in localnet -- ovn-northd-ddlog FAILED (ovn.at:6937)
 90: ovn -- send gratuitous arp with nat-addresses router in localnet -- ovn-northd ok
 91: ovn -- send gratuitous arp with nat-addresses router in localnet -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
 92: ovn -- delete mac bindings -- ovn-northd        ok
 93: ovn -- delete mac bindings -- ovn-northd-ddlog  ok
 94: ovn -- conntrack zone allocation -- ovn-northd  ok
 95: ovn -- conntrack zone allocation -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
 96: ovn -- tag allocation -- ovn-northd             ok
 97: ovn -- tag allocation -- ovn-northd-ddlog       FAILED (ovn.at:7148)
 98: ovn -- lsp deletion and broadcast-flow deletion on localnet -- ovn-northd ok
 99: ovn -- lsp deletion and broadcast-flow deletion on localnet -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
100: ovn -- ACL logging -- ovn-northd                ok
101: ovn -- ACL logging -- ovn-northd-ddlog          FAILED (ovs-macros.at:233)
102: ovn -- ACL rate-limited logging -- ovn-northd   ok
103: ovn -- ACL rate-limited logging -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
104: ovn -- same meter used by multiple logical flows -- ovn-northd ok
105: ovn -- same meter used by multiple logical flows -- ovn-northd-ddlog FAILED (ovn.at:7538)
106: ovn -- DSCP marking and meter check -- ovn-northd ok
107: ovn -- DSCP marking and meter check -- ovn-northd-ddlog FAILED (--wait=sb)
108: ovn -- read-only sb db:ptcp access -- ovn-northd ok
109: ovn -- read-only sb db:ptcp access -- ovn-northd-ddlog ok
110: ovn -- read-only sb db:pssl access -- ovn-northd ok
111: ovn -- read-only sb db:pssl access -- ovn-northd-ddlog ok
112: ovn -- nb connection/ssl commands -- ovn-northd ok
113: ovn -- nb connection/ssl commands -- ovn-northd-ddlog ok
114: ovn -- sb connection/ssl commands -- ovn-northd ok
115: ovn -- sb connection/ssl commands -- ovn-northd-ddlog ok
116: ovn -- nested containers -- ovn-northd          ok
117: ovn -- nested containers -- ovn-northd-ddlog    FAILED (ovs-macros.at:233)
118: ovn -- 3 HVs, 3 LRs connected via LS, source IP based routes -- ovn-northd ok
119: ovn -- 3 HVs, 3 LRs connected via LS, source IP based routes -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
120: ovn -- dns lookup : 1 HV, 2 LS, 2 LSPs/LS -- ovn-northd ok
121: ovn -- dns lookup : 1 HV, 2 LS, 2 LSPs/LS -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
122: ovn -- 4 HV, 1 LS, 1 LR, packet test with HA distributed router gateway port -- ovn-northd ok
123: ovn -- 4 HV, 1 LS, 1 LR, packet test with HA distributed router gateway port -- ovn-northd-ddlog FAILED (ovn.at:8790)
124: ovn -- 4 HV, 3 LS, 2 LR, packet test with HA distributed router gateway port -- ovn-northd ok
125: ovn -- 4 HV, 3 LS, 2 LR, packet test with HA distributed router gateway port -- ovn-northd-ddlog FAILED (ovn.at:9045)
126: ovn -- 1 LR with distributed router gateway port -- ovn-northd ok
127: ovn -- 1 LR with distributed router gateway port -- ovn-northd-ddlog FAILED (ovn.at:9265)
128: ovn -- send gratuitous arp for NAT rules on distributed router -- ovn-northd ok
129: ovn -- send gratuitous arp for NAT rules on distributed router -- ovn-northd-ddlog FAILED (ovn.at:9609)
130: ovn -- vlan traffic for external network with distributed router gateway port -- ovn-northd ok
131: ovn -- vlan traffic for external network with distributed router gateway port -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
132: ovn -- IPv6 ND Router Solicitation responder -- ovn-northd ok
133: ovn -- IPv6 ND Router Solicitation responder -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
134: ovn -- /32 router IP address -- ovn-northd      ok
135: ovn -- /32 router IP address -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
136: ovn -- 2 HVs, 1 lport/HV, localport ports -- ovn-northd ok
137: ovn -- 2 HVs, 1 lport/HV, localport ports -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
138: ovn -- 1 LR with HA distributed router gateway port -- ovn-northd ok
139: ovn -- 1 LR with HA distributed router gateway port -- ovn-northd-ddlog FAILED (ovn.at:10557)
140: ovn -- send gratuitous ARP for NAT rules on HA distributed router -- ovn-northd ok
141: ovn -- send gratuitous ARP for NAT rules on HA distributed router -- ovn-northd-ddlog FAILED (ovn.at:11115)
142: ovn -- ensure one gw controller restart in HA doesn't bounce the master -- ovn-northd ok
143: ovn -- ensure one gw controller restart in HA doesn't bounce the master -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
144: ovn -- IPv6 Neighbor Solicitation for unknown MAC -- ovn-northd ok
145: ovn -- IPv6 Neighbor Solicitation for unknown MAC -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
146: ovn -- options:requested-chassis for logical port -- ovn-northd ok
147: ovn -- options:requested-chassis for logical port -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
148: ovn -- options:requested-chassis with hostname -- ovn-northd ok
149: ovn -- options:requested-chassis with hostname -- ovn-northd-ddlog FAILED (ovs-macros.at:233)
150: ovn -- IPv6 periodic RA -- ovn-northd           ok
151: ovn -- IPv6 periodic RA -- ovn-northd-ddlog     FAILED (ovs-macros.at:233)
152: ovn -- ACL reject rule test -- ovn-northd       ok
153: ovn -- ACL reject rule test -- ovn-northd-ddlog FAILED (--wait=hv)
154: ovn -- Port Groups -- ovn-northd                ok
155: ovn -- Port Groups -- ovn-northd-ddlog          FAILED (ovs-macros.at:233)
156: ovn -- ACLs on Port Groups -- ovn-northd        ok
157: ovn -- ACLs on Port Groups -- ovn-northd-ddlog  FAILED (ovs-macros.at:233)
158: ovn -- Address Set generation from Port Groups (static addressing) -- ovn-northd ok
159: ovn -- Address Set generation from Port Groups (static addressing) -- ovn-northd-ddlog FAILED (ovn.at:12570)
160: ovn -- Address Set generation from Port Groups (dynamic addressing) -- ovn-northd ok
161: ovn -- Address Set generation from Port Groups (dynamic addressing) -- ovn-northd-ddlog FAILED (ovn.at:12622)
162: ovn -- ACL conjunction -- ovn-northd            ok
163: ovn -- ACL conjunction -- ovn-northd-ddlog     ERROR: Job failed: execution took longer than 1h0m0s seconds
```

**Comment by mbudiu-vmw** [comment]
One problem is that I can't run these tests locally:
`error: pathspec 'ddlog_ci16' did not match any file(s) known to git.`
is the error produced by ./test.sh ovn

File: rust/template/ovsdb/lib.rs (hunk 25 above)
[the remark this answers is not in the document]
Comment (ryzhyk) [reply rust/template/ovsdb/lib.rs:280]: Turns out that `table` here is the local OVSDB relation name (i.e., excluding the database name such as `OVN_Northbound`), but `translator` expects a fully qualified DDlog relation name. Let me try to come up with a fix.

File: rust/template/src/ovsdb_api.rs [hunk 26]
```diff
@@ -108,15 +108,23 @@ unsafe fn dump_delta(
     module: *const c_char,
     table: *const c_char,
 ) -> Result<CString, String> {
-    let table_str: &str = unsafe { CStr::from_ptr(table) }
+    let table_str: &str = CStr::from_ptr(table)
```
Comment (mbudiu-vmw) [inline rust/template/src/ovsdb_api.rs:111]: I would have saved a lot of time by avoiding these callbacks that you now removed.
I think this is cleaner too.

Comment (ryzhyk) [reply rust/template/src/ovsdb_api.rs:111]: Sorry, this was less obvious when looking at the diff in the PR.

File: src/Language/DifferentialDatalog/Compile.hs (hunk 15 above)
Comment (Kixiron) [reply src/Language/DifferentialDatalog/Compile.hs:1472]: My bad, use `::core::option::Option::Some`
