### PR TITLE
Capture stdout/stderr of processes invoked

### LINKED ISSUE #838: A way to read messages from Standard Error in Java API
Currently during compilation is something goes wrong it just logs the error in Standard Err and terminates. We should have a mechanism to return these error messages to the caller

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
Fixes #838
The class CompilationOutput is now available. It is passed as an argument to functions that compile generated programs.
After the compilation is finished the function gives access to the exit code and to stdout and stderr of the compilation processes.

### CODE REVIEW

File: java/ddlogapi/DDlogAPI.java [hunk 1]
```diff
@@ -659,33 +659,85 @@ public static String ddlogInstallationPath() throws DDlogException {
         return ddlogHome;
     }
 
+    public static class CompilationResult {
```
Comment (ryzhyk) [inline java/ddlogapi/DDlogAPI.java:662]: Do some of the methods in this class need to be synchronized because they can be invoked by the client as well as by the output reader threads this class spawns?

**Review by ryzhyk — APPROVED** [review]
@mbudiu-vmw, please merge if it's ready.

Gitlab CI is failing due to unrelated souffle test issue.
